config/routes.rb
Jlit::Application.routes.draw do

  root :to => 'static_pages#home'
  get "static_pages/home"
  get "static_pages/help"
  get 'about' => 'static_pages#about'
  get 'start' => 'static_pages#start'
  
  get 'genji' => 'static_pages#genji'
  get 'genji_warp' => 'static_pages#genji_warp'
  get 'genji_kidnap' => 'static_pages#genji_kidnap'
  get 'genji_secret' => 'static_pages#genji_secret'
  get 'genji_run' => 'static_pages#genji_run'
  get 'genji_fight' => 'static_pages#genji_fight'
  get 'genji_toothpick' => 'static_pages#genji_toothpick'
  get 'genji_katana' => 'static_pages#genji_katana'
  get 'genji_gun' => 'static_pages#genji_gun'
  get 'genji_drunk' => 'static_pages#genji_drunk'
  get 'genji_punishment' => 'static_pages#genji_punishment'
  get 'genji_conscience' => 'static_pages#genji_conscience'
  get 'genji_deal' => 'static_pages#genji_deal'
  
  get 'naomi' => 'static_pages#naomi'
  get 'naomi_warp' => 'static_pages#naomi_warp'
  get 'naomi_convince' => 'static_pages#naomi_convince'
  get 'naomi_gone' => 'static_pages#naomi_gone'
  get 'naomi_friend' => 'static_pages#naomi_friend'
  get 'naomi_refuse' => 'static_pages#naomi_refuse'
  get 'naomi_noroom' => 'static_pages#naomi_noroom'
  get 'naomi_ownroom' => 'static_pages#naomi_ownroom'
  get 'naomi_continue' => 'static_pages#naomi_continue'
  get 'naomi_beg' => 'static_pages#naomi_beg'
  get 'naomi_cry' => 'static_pages#naomi_cry'
  get 'naomi_strength' => 'static_pages#naomi_strength'
  get 'naomi_door' => 'static_pages#naomi_door'
  get 'naomi_in' => 'static_pages#naomi_in'
  
  get 'snow' => 'static_pages#snow'
  get 'snow_warp' => 'static_pages#snow_warp'
  get 'snow_wake' => 'static_pages#snow_wake'
  get 'snow_social' => 'static_pages#snow_social'
  get 'snow_observe' => 'static_pages#snow_observe'
  get 'snow_run' => 'static_pages#snow_run'
  
  get 'dunes' => 'static_pages#dunes'
  get 'dunes_warp' => 'static_pages#dunes_warp'
  get 'dunes_wake' => 'static_pages#dunes_wake'
  get 'dunes_dig' => 'static_pages#dunes_dig'
  get 'dunes_refuse' => 'static_pages#dunes_refuse'
  get 'dunes_widow' => 'static_pages#dunes_widow'
  get 'dunes_hostage' => 'static_pages#dunes_hostage'
  get 'dunes_swoon' => 'static_pages#dunes_swoon'
  get 'dunes_question' => 'static_pages#dunes_question'
  get 'dunes_threaten' => 'static_pages#dunes_threaten'
  get 'dunes_threaten2' => 'static_pages#dunes_threaten2'
  get 'dunes_swoon2' => 'static_pages#dunes_swoon2'
  get 'dunes_solo' => 'static_pages#dunes_solo'
  get 'dunes_nothing' => 'static_pages#dunes_nothing'
  get 'dunes_scoot' => 'static_pages#dunes_scoot'
  get 'dunes_leave' => 'static_pages#dunes_leave'
  get 'dunes_conspire' => 'static_pages#dunes_conspire'
  get 'dunes_run' => 'static_pages#dunes_run'
  get 'dunes_freedom' => 'static_pages#dunes_freedom'
  get 'dunes_capture' => 'static_pages#dunes_capture'
  get 'dunes_help' => 'static_pages#dunes_help'
  get 'dunes_fastforward' => 'static_pages#dunes_fastforward'
  get 'dunes_sleep' => 'static_pages#dunes_sleep'
  get 'dunes_ladder' => 'static_pages#dunes_ladder'
  

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
	GIA by Gorlan Yuen. 12/6/13
  </small>
  <nav>
    <ul>
      <li><%= link_to "Back to the Beginning", start_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <p id="logo">GIA</p>
      <%-# link_to "GIA", '#', id: "logo" -%>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "About",    about_path %></li>
          <%-# link_to "Sign in", '#' -%>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gorlan's Interactive Adventure</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
</head>

	<%= render 'layouts/header'%>

<div class="container">
	<body>
	
	<%= yield %>
	
	</body>
</div>

	<%= render 'layouts/footer'%>

</html>

app/views/static_pages/dunes.html.erb
<div class="center hero-unit">
	
	<h5>You decide to read Woman in the Dunes.</h5>
	<h5>You've seen the movie before; why not read the book as well?</h5>
	<h5>You pick up the book and look at its front and back covers.</h5>
	<h5>You hear a very low noise coming from the book.</h5>
	<h5>Surprised, you put the book to your ear to figure out what it is.</h5>
	<h5>Suddenly, sand pours out of the book's pages. It spills all over your face as you gasp in astonishment.</h5>
	<h5>The sand continues pouring until it fills your entire floor, and then higher.</h5>
	<h5>You try to shout for help, but the sand has just reached the height of your mouth and it abruptly silences you.</h5>
	<h5>You die a slow, choking death by drowning in sand.</h5>
	
	<%= link_to "Reincarnate", dunes_warp_path , class: "center btn" %>

</div>

app/views/static_pages/dunes_capture.html.erb
<div class="center hero-unit">
	
	<h5>A diet of minimal food and sand does not do the body good.</h5>
	<h5>You sprint for a maximum of 20 meters before your feet collapse.</h5>
	<h5>The villagers pick you up and throw you back in the pit.</h5>
	<h5>They confiscate your stepping blocks too.</h5>
	<h5>The rest of your life is spent in despair.</h5>
	<h5>Time and time again, you dream of the night you almost escaped.</h5>
	<h5>You sigh hopelessly and drift off into sleep.</h5>
	
	<%= link_to "Back to the Beginning", start_path %>
	
</div>

app/views/static_pages/dunes_freedom.html.erb
<div class="center hero-unit">
	
	<h5>You pick up the speed.</h5>
	<h5>The villagers are now chasing you.</h5>
	<h5>They can't catch up. They are running to capture a prisoner. You are running for life. For freedom.</h5>
	<h5>You laugh hysterically as they, one by one, stop to breathe.</h5>
	<h5>You glance back with excitement. At last, you can return home.</h5>
	<h5>While you are glancing back, you run facefirst into a tree surrounded by barbed pinecones.</h5>
	<h5>Blood gushes down your face and body and you drown in your own blood.</h5>
	<h5>You were so close too.</h5>
	
	<%= link_to "Back to the Beginning", start_path %>
	
</div>

app/views/static_pages/dunes_leave.html.erb
<div class="center hero-unit">
	
	<h5>You stand up.</h5>
	<h5>You go back in the house that the woman came from.</h5>
	<h5>You look around and see that it is a shelter with the bare necessities.</h5>
	<h5>You want to leave.</h5>
	<h5>But you can't.</h5>
	<h5>You spend the rest of your life in the sand pit, your freedom stripped away from you all because of one mistake.</h5>
	
	<%= link_to "Back to the Beginning", start_path %>
	
</div>

app/views/static_pages/dunes_question.html.erb
<div class="center hero-unit">
	
	<h5>"Why are you here?"</h5>
	<h5>The woman doesn't answer.</h5>
	<h5>"Who are you?"</h5>
	<h5>Still no answer.</h5>
	<h5>"Okay. I guess you don't want to talk."</h5>
	<h5>"Talking is a waste of energy," she finally says.</h5>
	<h5>Slowly but surely, the two of you make a connection. You learn more about her and she learns more about you. She too was forced in the pit against her will.</h5>
	
	<%= link_to "Conspire to escape", dunes_conspire_path , class: "center btn" %>
	
</div>

app/views/static_pages/dunes_swoon2.html.erb
<div class="center hero-unit">
	
	<h5>You decide to try and swoon her.</h5>
	<h5>You apologize to the woman for trying to hold her as hostage.</h5>
	<h5>She does not react.</h5>
	<h5>"Look I'm sure you want to get out of here just as much as I do."</h5>
	<h5>She goes back in the pit's house.</h5>
	<h5>Maybe that wasn't such a good idea.</h5>
	
	<%= link_to "You're on your own now", dunes_solo_path , class: "center btn" %>
	
</div>

app/views/static_pages/dunes_widow.html.erb
<div class="center hero-unit">
	
	<h5>The other person in the sand pit suddenly appears beside you.</h5>
	<h5>You take a look at her.</h5>
	<h5>She's beautiful.</h5>
	<h5>For a fleeting second, you consider staying in the dune if it meant you could spend more time with her.</h5>
	<h5>Nonsense, you think to yourself. This is not where I belong.</h5>
	<h5>An idea comes to you.</h5>
	
	<div class="btn-group">
	  <button class="btn"><%= link_to "Take the woman hostage.", dunes_hostage_path %></button>
	  <button class="btn"><%= link_to "Attempt to swoon her.", dunes_swoon_path %></button>
	  <button class="btn"><%= link_to "Question her.", dunes_question_path %></button>
	</div>
	
	
</div>

app/views/static_pages/genji_gun.html.erb
<div class="center hero-unit">
	
	<h5>You show the emperor's men no mercy as you mow them down with your relentless fury of a machine gun.</h5>
	<h5>They have no idea what is piercing through their bodies as the technology is beyond their time.</h5>
	<h5>You laugh maniacally as nobody can stop you.</h5>
	<h5>*Click* *Click* *Click*</h5>
	<h5>You should have brought that second round of ammunition.</h5>
	<h5>The remaining men swarm you and pierce your abdomen like yakinuki.</h5>
	<h5>At least you took some of them down.</h5>
	
	<%= link_to "Back to the Beginning", start_path %>
	
</div>

app/views/static_pages/genji_run.html.erb
<div class="center hero-unit">
	
	<h5>You run faster than you've ever run in your entire life.</h5>
	<h5>You regret everything you've ever done. If you could take it all back and do it over, you would.</h5>
	<h5>The emperor's men are quick and your stamina is limited. Your untrained feet are no match for their horses.</h5>
	<h5>You are captured and brought before the emperor.</h5>
	<h5>Your entire life flashes before your eyes as you are executed.</h5>
	<h5>Well, at least now, you have the opportunity to do it all over.</h5>
	
	<%= link_to "Back to the Beginning", start_path %>
	
</div>

app/views/static_pages/naomi_door.html.erb
<div class="center hero-unit">
	
	<h5>Naomi stands before you after you open the door.</h5>
	<h5>She has come back because she realizes she needs you. All the emotions you felt just a moment ago dissipate.</h5>
	<h5>You hug her with all your might, but she stands still.</h5>
	<h5>She wants you to continue to keep her under your shelter and pay for her needs.</h5>
	<h5>You agree without a second thought. You apologize profusely for being such a useless caretaker and promise it won't happen again.</h5>
	
	<%= link_to "Take her back in.", naomi_in_path , class: "center btn" %>
	
	
	
</div>

app/views/static_pages/naomi_gone.html.erb
<div class="center hero-unit">
	
	<h5>Naomi tilts her head and thinks.</h5>
	<h5>Despite your best efforts, she rejects your offer.</h5>
	<h5>You thank her for her time and the two of you part ways.</h5>
	<h5>You sit down and continue staring at her, wondering what could have been.</h5>
	
	<%= link_to "Back to the Beginning", start_path %>
	
	
</div>

app/views/static_pages/naomi_noroom.html.erb
<div class="center hero-unit">
	
	<h5>She throws a tantrum. You regret this immediately.</h5>
	<h5>Giving her own room would have been much less painful than this.</h5>
	
	<%= link_to "You concede.", naomi_ownroom_path , class: "center btn" %>
	
</div>

app/views/static_pages/snow_warp.html.erb
<div class="center hero-unit">
	
	<h5>The book is incredibly boring. You fall asleep in minutes</h5>
	<h5>Several hours later, you wake up in a drowsy state.</h5>
	<h5>You try to force yourself awake because class starts soon.</h5>
	<h5>After another hour, you manage to keep your eyelids up.</h5>
	
	<%= link_to "Wake Up", snow_wake_path , class: "center btn" %>
	
</div>

app/views/static_pages/start.html.erb
<div class="center hero-unit">
	
	<h5 class="center">You wake up one morning realizing that you did not do your literature homework.</h5>
	<h5 class="center">You were supposed to have read The Tale of Genji, Naomi, Snow Country, and Woman in the Dunes</h5>
	<h5 class="center">You only have enough time to read one of them. Which one do you choose?</h5>
	
	<%= link_to image_tag("tale_of_genji.jpg", width: 150, height: 200, alt: "The Tale of Genji"), genji_path %>
	<%= link_to image_tag("naomi.jpg", width: 150, height: 200, alt: "Naomi"), naomi_path %>
	<%= link_to image_tag("snow_country.jpg", width: 150, height: 200, alt: "Snow Country"), snow_path %>
	<%= link_to image_tag("woman_in_the_dunes.jpg", width: 150, height: 200, alt: "Woman in the Dunes"), dunes_path %>
	
</div>